name: flutter_assignment
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  oktoast: ^3.3.2
  dartz: ^0.10.1
  auto_route: ^7.8.4
  injectable: ^2.3.2
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  get_it: ^7.7.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  flutter_lints: ^3.0.0
  mocktail:
  bloc_test: 

 
flutter:

  uses-material-design: true

  assets:
    - asset/

  fonts:
      - family: Poppins
        fonts:
          - asset: fonts/Poppins-Regular.ttf
  
